### ISSUE TITLE
Add extra data and coordinate system to iolets

### ISSUE THREAD

**Issue by schmie** [hemelb-codes/hemelb#426]
**Reported by rupert on 6 Jun 2013 09:22 UTC**
For the virtual sites, I need to add a load of extra data to the iolets, including a coordinate system.

I have chosen to create a generic `ExtraData` class that is added to the iolet base class. The `ExtraData` can be subclassed to add particular required data. 

Also need to add a cross product to the `Vector3D`

**Comment by schmie** [comment]
**Comment by rupert on 6 Jun 2013 09:24 UTC**
5bf0fbd1a1da - add cross product to vector3d (and an `IsInRange` method)
91c337fa5e26 - create the extra data and define coordinate systems

**Comment by schmie** [comment]
**Modified by rupert on 6 Jun 2013 09:24 UTC**

**Comment by rupertnash** [comment]
I think this was done ages ago
