### ISSUE TITLE
Document and possibly rename LatticeData::GetProcIdFromGlobalCoords

### ISSUE THREAD

**Issue by mobernabeu** [hemelb-codes/hemelb#674]
`LatticeData::GetProcIdFromGlobalCoords` doesn't do what it says on the tin, i.e. it won't tell the MPI rank owning **any** lattice site given its global coordinates.

What does at the moment is probably fine for the LB algorithm but we shot ourselves in the foot while implementing IBM (see #652 and #668).

The method needs, at least, more documentation and possibly renaming.

**Comment by rupertnash** [comment]
This is now resolved
