### ISSUE TITLE
Dependencies are installed in source tree instead of under `CMAKE_INSTALL_PREFIX`

### ISSUE THREAD

**Issue by uschille** [hemelb-codes/hemelb#696]
Apparently the dynamic libraries are installed in `lib/` in the `dependencies/` directory in the source tree and the `CMAKE_INSTALL_PREFIX` is ignored. ~~This may be related to an issue with Jenkins on a CentOS node where some symlinks to the `*.so` files cannot be `lstat`ed causing a runtime error while loading shared libraries.~~

**Comment by rupertnash** [comment]
Just having a look over some open issues: As mentioned above, the superbuild uses `HEMELB_DEPENDENCIES_INSTALL_PATH` to determine where to install dependencies. I am NOT keen to change this.

However, we could certainly consider changing the default value from `${HEMELB_DEPENDENCIES_PATH} == ${HEMELB_ROOT_DIR}/dependencies` to `CMAKE_INSTALL_PREFIX`
