### ISSUE TITLE
Side effects in the build system that are totally unintuitive

### ISSUE THREAD

**Issue by uschille** [hemelb-codes/hemelb#698]
Some cmake switches/macros seem to have an effect on the dependencies even though they are given to the HemeLB cmake only. This can sometimes lead to different results depending on whether building from scratch or updating a previous build - thus defying the purpose of `make` and hampering reproducibility. See also #697.

**Comment by rupertnash** [comment]
Reviewing old issues just now: I *think* this one may be resolved by the new cmake setup that uses a single file (Code/cmake/options.cmake) to ensure consistency between the superbuild and code-only builds.

@uschille can you please close if this is the case?

**Comment by uschille** [comment]
The new cmake setup seems to be working fine so far. Thanks @rupertnash
