### ISSUE TITLE
RBC template cells: should mesh path be interpreted as relative to XML?

### ISSUE THREAD

**Issue by rupertnash** [hemelb-codes/hemelb#756]
Trying to load some of the example XML files gives errors like

`Red-blood-cell mesh file 'rbc_ico_2880.msh' does not exist`

It does exists, it's just no in the working directory, it's in the one that the XML input's in.

What is the desired behaviour? I'd suggest relative to the XML is correct as that's what we do for GMY.

**Comment by CharlesQiZhou** [comment]
@rupertnash We usually place the RBC mesh file (rbc_ico_2880.msh) in the same directory as the XML. And yes, it is supposed to be relative to the XML file just as the GMY does

**Comment by rupertnash** [comment]
So you have serendipitously not triggered the bug. This is an easy fix that will appear in rbc/merge soon
