### ISSUE TITLE
Bump ctemplate to 2.4 for Python3 compatibility

### ISSUE THREAD

**Issue by nickaj** [hemelb-codes/hemelb#760]
ctemplate v2.3 (as built by cmake) doesn't compile with Python3
ctemplate v2.4 does, with only a minor tweak to run `libtoolize` before the autogen.sh step

**Comment by rupertnash** [comment]
Thanks Nick - I did have a go at using 2.4 but missed the libtoolize step. The release hasn't been made quite correctly, has it? Any chance of a PR to `dependencies/ctemplate/find_or_build.cmake`?
