### ISSUE TITLE
Questions about .gmy file

### ISSUE THREAD

**Issue by FallenCastle** [hemelb-codes/hemelb#783]
Hi,
After using Hemelb for a few days, I found it an excellent opensource software. But I feel a bit confused about the Hemelb geometry file(*.gmy), may I ask where can I find some detailed explanation and description about the .gmy file? 
Best regards,
Fallen.

**Comment by sharplo** [comment]
Hi Fallen,
I am a developer of HemePure, which should use the .gmy files in the same format. You may take a look at this file: https://github.com/UCL-CCS/HemePure_tools/blob/master/vx2gmy/mpivx2gmy.cc
Hope this helps.
Best,
Sharp

**Comment by FallenCastle** [comment]
> Hi Fallen,
> I am a developer of HemePure, which should use the .gmy files in the same format. You may take a look at this file: https://github.com/UCL-CCS/HemePure_tools/blob/master/vx2gmy/mpivx2gmy.cc
> Hope this helps.
> Best,
> Sharp

Thanks a lot !

**Comment by rupertnash** [comment]
Hi @FallenCastle 

There is a description of the file format here: https://github.com/hemelb-codes/hemelb/blob/main/doc/dev/file-formats/geometry.md

There are also notes on how to build the geometry tool which can be used to generate them: https://github.com/hemelb-codes/hemelb/blob/main/doc/user/geometry-tool.md
