### ISSUE TITLE
Compiling program via superBuild fails due to code failures in CommandLineTests.cc.o 

### ISSUE THREAD

**Issue by behikh** [hemelb-codes/hemelb#797]
When running the superbuild to build the program, it fails building due to an error in the following test file: 
tests/configuration/CMakeFiles/test_configuration.dir/CommandLineTests.cc.o 

It seems to be due to a  code failures `error: no matching member function for call to 'FirstChildElement'` 

The superbuild runs and finishes if `HEMELB_BUILD_TESTS` are set to `OFF` in the following file: 
 hemelb/CMake/GlobalOptions.cmake 

Relevant stack trace/logs:

> [ 76%] Building CXX object tests/configuration/CMakeFiles/test_configuration.dir/CommandLineTests.cc.o
> In file included from /Users/behineh/Desktop/test/hemelb/Code/tests/configuration/CommandLineTests.cc:12:
> /Users/behineh/Desktop/test/hemelb/Code/tests/helpers/FolderTestFixture.h:38:36: error: no matching member function for call to 'FirstChildElement'
>           auto next_child = child->FirstChildElement(name);
>                             ~~~~~~~^~~~~~~~~~~~~~~~~

attached below is a text file with the complete stack trace/logs (from beginning of the build command until end):
[error.txt](https://github.com/hemelb-codes/hemelb/files/9961002/error.txt)

**Comment by rupertnash** [comment]
This is due to the TinyXML installed on your machine not being built with the `TINYXML_USE_STL` flag on.

Solution is probably to have the FindTinyXML cmake fail/reject the candidate if this flag isn't on.

**Comment by rupertnash** [comment]
You'll want to use somthing like
```
check_cxx_symbol_exists(TINYXML_USE_STL "${TINYXML_INCLUDE_DIR}/tinyxml.h" HAVE_TINYXML_USE_STL)
```
and add the `HAVE_TINYXML_USE_STL` var to `find_package_handle_standard_args`

https://cmake.org/cmake/help/latest/module/CheckCXXSymbolExists.html

**Comment by CharlesQiZhou** [comment]
Hi @rupertnash, on a related note, do `TINYXML_USE_STL` = YES/NO and `TIXML_USE_STL` = ON/OFF both serve a purpose or one has replaced the other? (cc @behikh)

**Comment by rupertnash** [comment]
So I used `TINYXML_USE_STL` in error, the correct name is `TIXML_USE_STL`

**Comment by rupertnash** [comment]
This may be fixed in main now. (I think the std::string -> C string conversion happens in the header so compiling the library with `TIXML_USE_STL` may not really matter)
