### ISSUE TITLE
Compiling and Running the gmy tool

### ISSUE THREAD

**Issue by amroabuzer** [hemelb-codes/hemelb#803]
Hello,
I recently found out about this project and I would like to say thank you for the great work!
Some background I'm currently trying to get the GPU HemeLB project going with my own stl files. I got everything setup and I'm currently trying to setup the geometry tool to convert my stl files to gmy files, but I'm stuck. 

**Issue**:
-  I tried following the steps from the geometry tool's documentation (i.e. I set up the gmy-tool environment) but when running
  ```
  pip install '.[gui]'
  ```
  I got the following issue:
  ![Screenshot from 2023-09-23 11-46-43](https://github.com/hemelb-codes/hemelb/assets/33330806/74cf39a8-4ab1-4380-88e8-f09e1abd84cd)
- Since vmtk is already in my package list I just commented out the vmtk requirement in setup.py
- After compiling and running hlb-gmy-gui I get this mystical OpenGL VTK issue and segmentation fault:
![Screenshot from 2023-09-23 11-48-50](https://github.com/hemelb-codes/hemelb/assets/33330806/a04195ba-2101-4630-833c-f446c9a31902)
- Might also be useful to say that I haven't compiled the hemelb project since I have the HemePureGPU already compiled and I'm currently only compiling the geometry tool 
I hope you can help me out here and thank you in advance

**Comment by c-denham** [comment]
Hello,
Were you able to resolve the issue @amroabuzer? I am having the same error, I have tried uninstalling and reinstalling the VTK and installed the OS packages but still get the following error:

![gmy-tool-warning](https://github.com/hemelb-codes/hemelb/assets/149164447/c51c100c-0af4-412c-85d2-9d4a25915078)

**Comment by rupertnash** [comment]
So we need to narrow down where your problems are. 

First, can your VTK open a render window correctly? (compile and run any VTK program that does this) 

second, can you open a render window from python? (In an interactive session, import VTK, read eg one of your STL files, create a render window, connect the output of your vtkSTLReader, and call interact a see VTK examples)

third, can vmtk open a window? (Try vmtksurfaceviewer with one of your STL files as an input)

**Comment by rupertnash** [comment]
I've had no response, so closing. Please reopen if this is an issue for you.
