### ISSUE TITLE
TinyXML Not found

### ISSUE THREAD

**Issue by Simosteinos** [hemelb-codes/hemelb#804]
Dear all,
I am trying to build the project, but I couldn't find a solution for this one:

`CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find TinyXML (missing: TINYXML_INCLUDE_DIR TINYXML_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/hemelb-main/CMake/FindTinyXML.cmake:31 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /home/hemelb-main/dependencies/TinyXML/find.cmake:7 (find_package)
  /home/hemelb-main/CMake/HemeLbDependency.cmake:8 (include)
  /home/hemelb-main/CMake/HemeLbDependency.cmake:54 (hemelb_dependency)
  CMakeLists.txt:76 (find_hemelb_dependency)`

I tried to follow this ticket [https://github.com/hemelb-codes/hemelb/issues/797](url) but always getting the same error.
Thanks in advance

**Comment by rupertnash** [comment]
Which CMake are you using? Superbuild or code-only? If the latter, do you have tinyxml installed?

**Comment by rupertnash** [comment]
Please reopen if this is still an issue
