### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by Mehdi1abbasi** [hemelb-codes/hemelb#805]
I encountered your open source code hemelb in a publication about red blood cells dynamics in the microvascular network. 
The first step is that I'm trying to compile the code but still receiving the same errors. It seems that the libraries needed are installed (see "cmake.txt" file). But when I wrote the command "make" it showed me too many errors as you see in file "make.txt".

Please, I'm writing to ask for help.

[make.txt](https://github.com/hemelb-codes/hemelb/files/13311670/make.txt)
[cmake.txt](https://github.com/hemelb-codes/hemelb/files/13311672/cmake.txt)

**Comment by rupertnash** [comment]
Your compiler does not support C++20 which is needed for HemeLB
