### ISSUE TITLE
Running hemelb with xml file <hemelbsettings version="3">

### ISSUE THREAD

**Issue by dpdclub** [hemelb-codes/hemelb#808]
Dear Developer of Hemelb,

I have been using the Pol-net by Miguel to generate xml and other files, but it seems they do not go with the latest version of Hemelb, giving the error, is there any way we can resolve this incompataility?  Thanks,

[Rank 0000001, 0.0s, mem: 0203468]: Unrecognised XML version. Expected 5, got 3

**Comment by mobernabeu** [comment]
Hi @dpdclub, do you generate the xml file within PolNet and then try to run the simulation on separate installation of HemeLB?

**Comment by dpdclub** [comment]
Hi Miguel,

Yes, I generated all the preprocessed file using polnet installed in the Docker container and then I plan to use HemeLB to run all the cases on server. Because I cannot run Docker on server.

He


________________________________

**Comment by rupertnash** [comment]
Use `hemelb-confcheck` to tell you about problems in your XML configuration files. You will have to update any old XML files, either by hand or write a small script to do it.

**Comment by mobernabeu** [comment]
Thanks @rupertnash.

@dpdclub, the proper solution would be to update the version of the setup tool within PolNet, but I wonder whether you might get your results quicker by simply tweaking the XML files rather than waiting for me to do that (going on leave after tomorrow)?

**Comment by dpdclub** [comment]
Hi Rupert and Miguel,


Thanks for your comments. Could you please point me to introduction of the standard format of XML for the latest version of Hemelb. I will convert the old ones.

He
________________________________

**Comment by rupertnash** [comment]
https://github.com/hemelb-codes/hemelb/blob/main/doc/user/XmlConfiguration.md
